### ISSUE TITLE
Handle AWS::Include transform

### ISSUE THREAD

**Issue by fireflycons** [fireflycons/Firefly.CloudFormation#14]
Template parser should handle macro transforms without throwing an error

The following will throw an error saying that the resource type cannot be determined
```yaml
Resources:
  Bucket:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: s3://MyAmazonS3BucketName/MyFileName.yaml
```
